#!/bin/sh

# This file should be located in .git/hooks/post-receive

# Checkout location
git --work-tree=/var/projects/project --git-dir=/var/repos/repo.git checkout -f

# Working directory
cd /var/projects/urekon-api

# Install dependencies
composer install

# Environment config
echo "
APP_ENV=production
DB_HOST=127.0.0.1
DB_DATABASE=<yourdatabase>
DB_USERNAME=<username>
DB_PASSWORD=<password>
" > .env

# File permissions
chown -R www-data:www-data *
