#!/bin/sh

# This file should be located in .git/hooks/post-receive

REP_PATH=<your-repo-path>
SRC_PATH=<your-project-path>

# Checkout location
git --work-tree=$SRC_PATH --git-dir=$REP_PATH checkout -f

# Working directory
cd $SRC_PATH

# Install dependencies
composer install

# Migrate database
php artisan migrate

# Environment config
echo "
APP_ENV=production
DB_HOST=127.0.0.1
DB_DATABASE=<yourdatabase>
DB_USERNAME=<username>
DB_PASSWORD=<password>
" > .env

# File permissions
chown -R www-data:www-data *
